alias mkdir="mkdir -p"
alias c="clear; tmux clear-history"
alias cdc="cd; clear; tmux clear-history"

alias t="task"
alias tw="taskwarrior-tui"

alias v="f -e nvim"

alias nnn="TERM=xterm-256color nnn -C ."
alias n="nnn"

alias ni="npm install"
alias nid="npm install --save-dev"
alias ng="npm install -g"
alias nr="npm run"
alias ns="npm start"
alias yd="yarn add"
alias ydd="yarn add --dev"

alias nv="nvim"
alias nvf="nvim -c Files"
alias nvr="nvim -c Rg"
alias nvn="nvim -c NnnPicker"
alias nvg="nvim -c Git"
alias nvp="nvim -c PackerSync"
alias vimdiff="nvim -d"

alias b="brew"
alias bi="brew install"
alias bu="brew uninstall"
alias bubu="brew update && brew upgrade"
alias bs="brew search"
alias bss="brew services"

alias exa="exa --classify"
alias ext='exa --tree --level'

alias tls="tmux list-sessions"
alias td="tmux detach"
alias ta="tmux attach-session -t"
alias tn="tmux new-session -s"
alias tksv="tmux kill-server"
alias tkss="tmux kill-session -t"

alias mx="tmuxinator"
alias mxs="tmuxinator start"
alias mxe="tmuxinator edit"
alias mxn="tmuxinator new"
alias mxc="tmuxinator copy"

alias g="git"
alias lg="lazygit"
alias ga="git add"
alias gai="git add --interactive"
alias gd="git diff"
alias gr="git rebase"
alias gri="git rebase --interactive"
alias gc="git commit --verbose"
alias gcf="git commit --all --fixup"
alias gco="git checkout"
alias gcp="git checkout --patch"
alias gs="git stash"
alias gsp="git stash pop"
alias gss="git stash push --patch"
alias gcl="git clone"
alias gcL="git clean -i"
alias gm="git merge"
alias gP="git push"
alias gf="git fetch"
alias gl="git pull"
alias glo="git log"
alias gst="git status"
