#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           8
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true

killall "sxhkd"
sxhkd &
clipmenud &
