vim.api.nvim_set_var("buftabline_show", 2)
vim.api.nvim_set_var("buftabline_numbers", 2)
vim.api.nvim_set_var("buftabline_indicators", 1)

vim.api.nvim_set_keymap("n", "<Leader>1", "<Plug>BufTabLine.Go(1)", {})
vim.api.nvim_set_keymap("n", "<Leader>2", "<Plug>BufTabLine.Go(2)", {})
vim.api.nvim_set_keymap("n", "<Leader>3", "<Plug>BufTabLine.Go(3)", {})
vim.api.nvim_set_keymap("n", "<Leader>4", "<Plug>BufTabLine.Go(4)", {})
vim.api.nvim_set_keymap("n", "<Leader>5", "<Plug>BufTabLine.Go(5)", {})
vim.api.nvim_set_keymap("n", "<Leader>6", "<Plug>BufTabLine.Go(6)", {})
vim.api.nvim_set_keymap("n", "<Leader>7", "<Plug>BufTabLine.Go(7)", {})
vim.api.nvim_set_keymap("n", "<Leader>8", "<Plug>BufTabLine.Go(8)", {})
vim.api.nvim_set_keymap("n", "<Leader>9", "<Plug>BufTabLine.Go(9)", {})
vim.api.nvim_set_keymap("n", "<Leader>0", "<Plug>BufTabLine.Go(0)", {})
